# Hard Work - Делаем тесты хорошими

## Пример 1

Похоже на то, как это описывалось в занятии, имеем код, который уведомляет клиента о загрузке данных с его отчетами.
Отправка осуществлялась функцией

```python
async def sidetask_send_email_to_client(params: ParametersDataclass) -> None:
    dt = params.date
    email_list = params.pepsiru_email_list
    url = '...'
    data = {
        "message_header": "RDA_data",
        "message": f"Сформированы данные за {dt}",
        "emails": email_list,
    }
    async with aiohttp.ClientSession() as session:
        async with session.post(url, json=data) as response:
            response_data = await response.json()
    assert response_data["answer"]
    log.info("EMAIL: sent emails to Clinet")
```

В таком виде изначально не писал тестов для отправки писем (фактически тестировали на практике, отправляя письма не тестовые адреса), в том числе потому что считал, что здесь нужно использовать моки. Однако до этого занятия у меня складывалось впечатление, что моков нужно избегать как можно дольше.

С учетом полученных знаний, проверим как теперь вызывается пост запрос, и с какими данными.

```python
import pytest
from unittest.mock import AsyncMock, patch
from src.sidetask import sidetask_send_email_to_client, ParametersDataclass

TESTED_POST_MODULE = 'aiohttp.ClientSession.post'

@pytest.mark.asyncio
async def test_sidetask_send_email_to_client():
    # Создадим экземпляр класса с параметрами
    test_params = ParametersDataclass(
        date="2024-01-25",
        email_list=["email1@example.com", "email2@example.com"] # адреса не важны
    )

    # Mock чтобы симулировать ответ
    mock_response_data = {"answer": True}

    # Патчим метод, который используется для POST запроса
    with patch(TESTED_POST_METHOD, new_callable=AsyncMock) as mock_post:
        mock_post.return_value.__aenter__.return_value.json = \
            AsyncMock(return_value=mock_response_data)

        # Вызов тестируемой функции
        await sidetask_send_email_to_client(test_params)

        # Проверяем, что POST запрос был вызван с корректными данными
        mock_post.assert_called_once()
        called_args, called_kwargs = mock_post.call_args
        assert called_kwargs["json"]["message_header"] == "RDA_data"
        assert called_kwargs["json"]["message"] == f"Get data from {test_params.date}"
        assert called_kwargs["json"]["emails"] == test_params.pepsiru_email_list
```

Можно обратить внимание, что теперь теоретически можно тестировать любую внешнюю зависимость, которая фактически делает POST запрос, указав ее в переменной  TESTED_POST_MODULE

Моки: используем внешнюю зависимость как мок (`aiohttp` в данном случае) и мокаем фактически возвращаемый `response`. Таким образом мы действительно тестируемся на абстрактном уровне, не затрагивая фактический механизм отправки пост запроса (и тестируем только наш код, а не стороннюю зависимость).

## Пример 2

Имеется простой класс для считывания конфига из `YAML` файла.
Изначально, тестов для него также не писалось, по причине, аналогичной как в примере 3.

В целом, при проверке можем выделить следующие свойства:

```python
class ConfigParserYAML:
    def __init__(self, config_file: str = "config.yaml") -> None:
        self.config = None
        self.stages = None
        self.dates = None

        config_file_path = os.path.abspath(config_file)
        log.info(config_file_path)
        try:
            with open(config_file_path, "r") as configfile:
                parsed_yaml = yaml.safe_load(configfile)
        except FileNotFoundError:
            log.error("Config file not found")
            sys.exit(-1)
        self.config = TasksConfig(**parsed_yaml)
```

- Корректное считывание конфига, когда файл существует и валидный
- Корректное возникновение ошибки если файл не существует
- Корректное возникновение ошибки, если содержимое не валидно

```python
import os
import sys
import pytest
from unittest.mock import mock_open, patch
from src.config_parser import ConfigParserYAML 

# Sample YAML для тестирования
sample_yaml_content = """
stages:
  - stage1
  - stage2
dates:
  start: '2021-01-01'
  end: '2021-12-31'
"""

def test_config_parser_yaml_with_valid_file():
    # Мокаем октрытие файла
    with patch("builtins.open", mock_open(read_data=sample_yaml_content)):
        parser = ConfigParserYAML("config.yaml")
        assert parser.config is not None
        assert parser.stages == ["stage1", "stage2"]
        assert parser.dates == {"start": "2021-01-01", "end": "2021-12-31"}

def test_config_parser_yaml_file_not_found():
    with patch("os.path.abspath", return_value="/path/to/config.yaml"):
        # Мок open() чтобы вызывал FileNotFoundError
        with patch("builtins.open", side_effect=FileNotFoundError):
            with pytest.raises(SystemExit) as e:
                ConfigParserYAML("config.yaml")
            # Корректно ли выходим из программы?
            assert e.type == SystemExit
            assert e.value.code == -1

@pytest.mark.parametrize("invalid_yaml", ["invalid YAML content", ""])
def test_config_parser_yaml_with_invalid_yaml(invalid_yaml):
    with patch("builtins.open", mock_open(read_data=invalid_yaml)):
        # Корректно вызывается YAMLError
        with pytest.raises(yaml.YAMLError):
            ConfigParserYAML("config.yaml")
```

Моки: на открытие файла и содержимое - не используем реальные файлы для тестирования (альтернативно, возможно, создавать виртуальные файлы).

Теперь независимо проверяем, что собственно парсинг конфига происходит, и при возникновении проблем корректные исключения возникают.

## Пример 3

Имеем простую реализацию функции, которая использует билиотеку `Slack Bolt` для взаимодействия с `Slack` из Python.

Самый простой пример, команда выполняется из `Slack`, делает запрос в БД и возвращает текущее состояние парсеров.

```python
@app.command("/check_parsers")
def parsers_command(ack, say, logger):
    # Acknowledge command request
    ack("Fetching data from DB")
    try:
        result = get_parsers_data()
        logger.info(result)
        say(result)
    except Exception as e:
        logger.error(e)
```

Теперь мы уже имеем в виду, что подобные функции вполне поддаются написанию юнит-тестов, хотя тут идет плотное взаимодействие с внешним миром через стороннюю зависимость.

Проверяем свойства:

- При успешном выполнении, функция получает запрос, получает данные (здесь замена на мок), сообщает результат
- При ошибке, корректно вызывается исключение.

```python
import pytest
from unittest.mock import Mock, patch
from src.app import app

def test_parsers_command_success():
    # Создаем моки
    ack = Mock()
    say = Mock()
    logger = Mock()
    mock_result = "mocked data"

    # Мокаем get_parsers_data
    with patch("src.queries.get_parsers_data", return_value=mock_result):
        app.parsers_command(ack, say, logger)

        ack.assert_called_with("Fetching data from DB")
        logger.info.assert_called_with(mock_result)
        say.assert_called_with(mock_result)

def test_parsers_command_exception():
    # Создаем моки
    ack = Mock()
    say = Mock()
    logger = Mock()
    mock_exception = Exception("mocked exception")

    # Мокаем get_parsers_data, чтобы вызывалось исключение
    with patch("path.to.get_parsers_data", side_effect=mock_exception):
        app.parsers_command(ack, say, logger)

        ack.assert_called_with("Fetching data from DB")
        logger.error.assert_called_with(mock_exception)
        # Проверяем что `say` не был вызван после ошибки
```

Моки: используем все, что предоставлет `Slack Bolt` как моки. Также мокаем нашу функцию, которая делает запрос в БД (потому что это не задача этого теста).
В итоге остается только скелет того, что выполняется непосредственно этим кодом.
Такую структуру легко использовать и для тестирования более сложных команд.

## Пример 4

Пример, аналогичный приводимому в прошлом занятии.

Для тестирования асинхронных запросов в `Clickhouse` использовали `Docker` контейнер с бд, чтобы проверить, что запросы выполняются корректно.

В прошлый раз мы правильно выделили свойсво, а именно - корректный вызов выполнения асинхронного запроса.
Чтобы этот эффект был достаточно абстрактным, проверяем именно вызов на выполнение запроса. В то же время не зависим от конкретной реализации предлагаемых сторонними библиотеками решений для выполнения асинхронного взаимодействия с БД.

Однако мы всё ещё зависим от БД, пусть даже она тестовая и поднимается в контейнере.

Чтобы проверить абстрактное свойство, нужно убедиться,
что корректно вызывается метод, который отвечает за выполнение запроса, причем реализация конкретного кода, выполняющего запроса может быть любой.

```python
# Кусочек кода
@pytest.fixture
def process_config(self):
    p_config = MagicMock()
    dsn = "clickhouse+asynch://username:password@clickhouse:9000/db1"
    a_engine = create_async_engine(dsn)
    metadata = MetaData(a_engine)
    p_config.get_click_async_metadata.return_value = metadata
    p_config.get_click_async_engine.return_value = a_engine
    p_config.get_date.return_value = datetime.strptime("2023-06-01", "%Y-%m-%d")
    yield p_config

def test_agg_en_stock_with_tmp_tables(self, process_config) -> None:
    agg_en = Aggregation(process_config)
    asyncio.run(agg.create_tmp_category_table())
```

Для этого изменим тест следующим образом, чтобы все элементы, имеющие отношение к работе с БД, были моками:

```python
import pytest
from unittest.mock import MagicMock, create_autospec
from sqlalchemy.ext.asyncio import AsyncEngine
from sqlalchemy.schema import MetaData
from datetime import datetime

@pytest.fixture
def process_config():
    p_config = MagicMock()
    # Mock the async engine
    a_engine = create_autospec(AsyncEngine, instance=True)
    # Mock the metadata
    metadata = create_autospec(MetaData, instance=True, bind=a_engine)

    p_config.get_click_async_metadata.return_value = metadata
    p_config.get_click_async_engine.return_value = a_engine
    p_config.get_date.return_value = datetime.strptime("2023-06-01", "%Y-%m-%d")
    yield p_config

def test_agg_en_stock_with_tmp_tables(self, process_config) -> None:
    agg_en = Aggregation(process_config)
    asyncio.run(agg.create_tmp_category_table())
```

Моки: используем моки для движка ORM и метадаты, чтобы не зависеть от кода БД.

## Пример 5

Сервис для увеличения ресурсов на БД.

```py
@contextmanager
def upscaling_downscaling() -> None:
    try:  # noqa
        response = requests.patch(
            scale_url,
            json=upscale,
            auth=(CLICK_KEY_ID, CLICK_KEY_SECRET),
        )
        assert response.status_code == 200
        log.info("UPSCALING CLICK API")
        _wait_for_api_upscale(UPSCALE_MAX_VALUE // 3)
        min_total_memory_response = response.json()['result']['minTotalMemoryGb']
        max_total_memory_response = response.json()['result']['maxTotalMemoryGb']
        log.info("UPSCALE CLICK API: minTotalMemoryGb -> %s",
                    min_total_memory_response)
        log.info("UPSCALE CLICK API: maxTotalMemoryGb -> %s",
                    max_total_memory_response)
        yield
    except Exception as e:
        log.error(e)
        raise e
    finally:
        try:
            response = requests.patch(
                scale_url,
                json=downscale,
                auth=(CLICK_KEY_ID, CLICK_KEY_SECRET),
            )
            assert response.status_code == 200
            min_total_memory_response = response.json()['result']['minTotalMemoryGb']
            max_total_memory_response = response.json()['result']['maxTotalMemoryGb']
            log.info("DOWNSCALE CLICK API: minTotalMemoryGb -> %s",
                     min_total_memory_response)
            log.info("DOWNSCALE CLICK API: maxTotalMemoryGb -> %s",
                     max_total_memory_response)
        except Exception as e:
            log.error(e)
            raise e
```

Свойства, которые необходимо протестировать:

- Корректно вызывается запрос, связанный с увеличением ресурсов (но это тестируется без прямого взаимодействия с реальным реквестом).
- Корректно вызывается исключение при ошибке.

```python
import pytest
from unittest.mock import patch, Mock
from src.upscaling import upscaling_downscaling  # Import your context manager

def test_upscaling_downscaling_success():
    # Мокаем ответ requests.patch
    mock_response = Mock()
    mock_response.status_code = 200
    mock_response.json.return_value = {
        'result': {'minTotalMemoryGb': '10', 'maxTotalMemoryGb': '20'}
    }

    with patch('requests.patch', return_value=mock_response) as mock_patch
        with upscaling_downscaling():
            pass

        # Убеждаемся, что requests.patch был вызван корректно для изменения ресурсов
        assert mock_patch.call_count == 2

def test_upscaling_downscaling_exception():
    mock_response = Mock()
    mock_response.status_code = 500
    mock_response.json.return_value = {}

    with patch('requests.patch', return_value=mock_response) as mock_patch
        with pytest.raises(Exception):
            with upscaling_downscaling():
                pass

        # Убеждаемся что requests.patch был взыван единожды для апскейла
        assert mock_patch.call_count == 1
```

Моки: для библиотеки `requests`, связанные с HTTP запросами.

## Выводы

Это занятие изменило мое понимание использования моков. Раньше я старался избегать их использования как можно сильнее, потому что при их использовании возникает ощущение, что тест не отражает реальную работу программы.
Однако это противоречит с тем, что тест должен проверять только написанный нами функционал и не должны отвечать за взаимодействие с внешним миром.

В таком случае, использование моков практически неизбежно, если мы не хотим, чтобы наши тесты не зависили от реализации.

Теперь мне проще думать о том, что тесты не отличаются в этом смысле от самого программного кода - мы должны пытаться сделать их как можно более независимым элементом, не связанным с реализацией, и проверяющим правильность кода именно как абстракции.
