# Hard Work - Логика Хоара для программистов 3

## Пример 1

Имеем функцию, которая ищет sql файлы в проекте по указанному имени и корневой директории:

```py
def get_sql_by_name(
    file_name: str,
    root_dir: Optional[pathlib.Path] = None,
) -> str:
    """
    Pre:  
        файл с таким названием c расширением .sql 
        существует в root_dir или поддиректориях
    Post: 
        возвращает содержимое .sql файла в формате str
    """
    file_name += ".sql"
    if not root_dir:
        root_dir = pathlib.Path(__file__).absolute().parent
    for file_path in root_dir.glob("**/*"):
        if file_path.name == file_name:
            break
    else:
        raise Exception(f"No such file {file_name} in {root_dir}")
    with pathlib.Path(file_path).open('r') as f:
        return f.read()
```

На самом деле возможно эта функция слишком специфична по отношению именно к .sql
файлам, мы могли бы ослабить её предусловие, чтобы она искала и возвращала содержимое любых
файлов (например конфигов).

```py
def get_file_by_name(
    file_name: str,
    root_dir: Optional[pathlib.Path] = None,
    file_ext: str,
) -> str:
    """
    Pre:  
        file_ext: формата .ext
        файл с таким названием c расширением `file_ext`
        существует в `root_dir` или поддиректориях
    Post: 
        возвращает содержимое файла в формате str
    """
    assert filex_ext.startswith('.')
    file_name += file_ext
    if not root_dir:
        root_dir = pathlib.Path(__file__).absolute().parent
    for file_path in root_dir.glob("**/*"):
        if file_path.name == file_name:
            break
    else:
        raise Exception(f"No such file {file_name} in {root_dir}")
    with pathlib.Path(file_path).open('r') as f:
        return f.read()
```

Название функции больше не имеет смысла и лучше заменить на `get_file_by_name`
также стоит передавать расширение файла как дополнительный аргумент, хотя
это "ломает" сигнатуру функции. В любом случае, если не вводить агрумент по умолчанию,
это изменение затрагивает использование функции в проекте.

Есть, однако, идея, как усилить постусловие: можно вернуть расширение файла с его содержимым,
чтобы позволить клиенту функции воспользоваться этой информацией при обработке содержимого.

```py
# Post: 
#     возвращает содержимое файла в формате str и его расширение
return (f.read(), file_ext)
```


## Пример 2

Функция, которая выделяет ресурсы для выполнения задач на одной из нод
Clickhouse.

Предусловием будет то, что "источником" задачи должен быть Clickhouse.

```py
def allocate_task_resources(my_task: MyTask) -> Resource:
    """
    Предусловие: 
        my_task.source == ActionSource.CLICKHOUSE
    Посусловие: 
        возвращается значение Resource.NODE или 
        Resource.FAIL, если выделение ресусров не произвошло успешно
    """
    logger = get_run_logger()
    if my_task.source != ActionSource.CLICKHOUSE:
        raise ValueError("Не применимо для этой задачи")
    click_resources = get_node_resource_usage()
    for node, res in click_resources.items():
        if my_task.estimated_weight <= res:
            logger.debug(f"allocate_task_resources:node={node}")
            return node
    logger.debug(f"allocate_task_resources:node={Resource.FAIL}")
    return Resource.FAIL
```

Но мы можем ослабить предусловие, если будем возвращать Resource всегда,
если он не применим можно вернуть что-то вроде Resource.NA (не применимо):

```py
def allocate_task_resources(my_task: MyTask) -> Resource:
    """
    Посусловие: 
        возвращается значение Resource.NODE или 
        Resource.FAIL, если выделение ресусров не произвошло успешно
    """
    logger = get_run_logger()
    match my_task.source:
        case ActionSource.CLICKHOUSE:
            click_resources = get_node_resource_usage()
            for node, res in click_resources.items():
                if my_task.estimated_weight <= res:
                    logger.debug(f"allocate_task_resources:node={node}")
                    return node
            logger.debug(f"allocate_task_resources:node={Resource.FAIL}")
            return Resource.FAIL
        case _:
            logger.debug(f">>>allocate_task_resources:node={Resource.NA}")
            return Resource.NA
```

(Я не уверен, считать ли потенциальный `raise` частью постусловия).
В итоге:

- Изменили реализацию функции `allocate_task_resources`
- Добавили к `Resource` (это Enum) вариант `Resource.NA`
- Требование предусловия ушло
- Постусловие: возвращается значение Resource всегда, не возникает `exception` `ValueError`, постусловие стало более "узким".

## Пример 3

Возможно, немоного искуственные пример, так как подобный стиль написания и
так подразумевается по умолчанию (иначе это code-smell).
Но допустим у нас есть ресурс, котором мы хотели бы воспользоваться, но который
затем нужно после использования высвободить:

```py
def get_connect_cdriver() -> cd.Client:
    """
    Пред: предыдущий клиент закрыт 
    """
    return cd.Client(
        host=st.CLICK_DB_HOST,
        database=st.CLICK_DB_NAME,
        user=st.CLICK_DB_USER,
        password=st.CLICK_DB_PASSWORD,
        port=st.CLICK_DB_PORT,
        secure=True,
        verify=False,
    )
```

Здесь контекстный менеджер приходит на выручку: автоматизируется управление ресурсом,
мы можем быть убеждены, что в прошлый раз коннект всегда закрыт (`finally: conn.disconnect()`),
что даст нам ослабление предусловия. Но одновременно с этим усилилось (появилось) постусловие - 
добавилось автоматическое закрытие ресурса.

```py
@contextmanager
def get_connect_cdriver() -> cd.Client:
    """
    Пост: коннект закрыт после использования 
    """
    conn = cd.Client(
        host=st.CLICK_DB_HOST,
        database=st.CLICK_DB_NAME,
        user=st.CLICK_DB_USER,
        password=st.CLICK_DB_PASSWORD,
        port=st.CLICK_DB_PORT,
        secure=True,
        verify=False,
    )
    try:
        yield conn
    finally:
        conn.disconnect()
```

## Пример 4

Имеем функцию, которая собирает вместе и возвращает для задачи глобальные параметры
и параметры, относящиеся к задаче.

Параметры, относящиеся к задаче описываются в файле-конфиге.
Если соответствие не найдено, во выбрасывается исключение.

```py
def get_action_kwargs(flow_name: str, args: List[str]) -> Dict[str, Any]:
    """
    Предусловие:
        flow_name должен иметь соответствие в файле-конфиге в run_conf
    Пост:
        Вовращает словарь типа {"parameter1": "value1", "parameter2": "value2"}
        состоящий из глобальных параметров и параметров задачи
    Raises:
        KeyError
    """

    run_conf = get_run_config().dict()
    global_args = run_conf["global_conf"]
    try:
        task_specific_args = run_conf[flow_name]
    except KeyError:
        logger.error(f"{flow_name} have no match in config file!")
        raise KeyError
    return global_args | task_specific_args
```

Если подумать, то бывает что мы не хотим описывать для некой задачи параметры к конфиге
(например, это просто не требуется). Поэтому можно ослабить предусловие и изменить
реализацию:

```py
def get_action_kwargs(flow_name: str, args: List[str]) -> Dict[str, Any]:
    """
    Пост:
        Вовращает словарь типа {"parameter1": "value1", "parameter2": "value2"}
        состоящий из глобальных параметров и/или(!) параметров задачи
    """
    run_conf = get_run_config().dict()
    global_args = run_conf["global_conf"]
    task_specific_args = run_conf.get(flow_name, {})
    return global_args | task_specific_args
```

С точки зрения изменений в постусловиях, то мы скорее ослабили их, так как теперь
функция может без предупреждений не включать параметры задачи, в случае, например, опечатки.
Это наглядный пример того, что вероятно, не стоит так изменять функцию, чтобы ослабление
предусловий приводило к ослаблению постусловий.
    
## Пример 5

Функция для получения диапазона дат между 2 значениями:

```py
def get_daterange(date1: datetime, date2: datetime) -> list[datetime]:
    """
    Предусловие:
        Дата1 должна быть меньше, чем дата2
    Пост:
        Возвращается список дат (дней) меджу date1 и date2
    """
    if date1 > date2:
        raise ValueError(f"{date1} > {date2}]")
    return [
        date1 + timedelta(days=x)
        for x in range((date2 - date1).days + 1)
    ]
```

Допустим, мы хотели бы ввести любые 2 даты и получить диапазон между ними:

```py
def get_daterange(date1: datetime, date2: datetime) -> list[datetime]:
    """
    Пост:
        Возвращается список дат (дней) меджу date1 и date2
    """
    if date1 > date2:
        date1, date2 = date2, date1
    return [
        date1 + timedelta(days=x)
        for x in range((date2 - date1).days + 1)
    ]
```

В этом случае мы ослабили предусловие, фактически исключив его.
Теперь даты могут прийти в функцию в любом порядке и она выдаст корректный результат.
(На самом деле не факт, что это хорошо, потому что перепутанный порядок значений может
быть признаком ошибок в другом месте, но это всё зависит от контекста).
Если мы считаем вызов исключения частью постусловия, то в этом случае мы
также ужесточили (сузили) постусловие.

## Выводы

Честно говоря, не на 100% уловил идею о том, что более слабые предусловия связаны с
более сильными постусловиями, однако действительно почти всегда такое изменение 
ведёт к более универсальному коду. Написание в таком стиле затем даёт нам функции,
которые проще переиспользовать (открывая, например, файлы разных расширений).

Но также нужно отметить, что изменения такого рода (ослабление предусловий, усиление
постусловий) являются "разрущающими" - т.е. вынуждают нас вносить изменения в реализацию и
в окружающий код. При этом если этот код уже используется, всегда есть риск пропустить
пользователя измененной нами функции, что приведёт к ошибке. Об этом как раз и говорит
нам приници подстановки Лисков.

Поэтому правильным подходом будет, естественно, изначальное написание функций с в разумных пределах
свободным "входом" и определённым "выходом". Такими функциями, как деталями
удобно пользоваться в разных частях проекта. Однако нужно учитывать, что более свободные
предусловия вероятно потребуют больше валидаций и проверок в реализации.
